version: '3.7'

services:
  backend:
    build: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes: 
      - ./backend:/app
    expose:
      - 8000
  frontend:
    build: ./frontend
    command: npm start
    volumes: 
      - ./frontend:/app
    expose:
      - 8080
    environment:
      - NODE_ENV=development
    depends_on:
      - backend
  reverse_proxy:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - backend
      - frontend
